apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: ghcr.io/shipperizer/starwars-docker
    custom:
      buildCommand: ./buildx.sh
      dependencies:
        dockerfile:
          path: Dockerfile
  local:
    push: true
